export const currentProjects = [
  {
    img: "/projects/bandstats.png",
    title: "BandStats",
    link: "/bandstats",
    linkCode: "https://github.com/enmourn/bandstats",
    description: "Simple and convenient tool for evaluating the activity of a group and its members",
    techStack: "React, React Router, Chakra, Chart.js, Firebase, Vite",
    toDo: "Add month statistic",
  },
  {
    img: "./projects/collagepro.png",
    title: "Collage Pro",
    link: "/collagepro",
    description: `Collage maker with the ability to change canvas, template, save project localy and
      getting preview and final image`,
    techStack: "Preact, Typescipt, Zustand, Styled Components, Vite",
    toDo: "Fix rendering bugs, create image optimization, redesign sidebar, make mouse control, add image filters",
  },
  {
    img: "./projects/lost-in-the-forest.png",
    title: "Lost In The Forest",
    link: "/lost-in-the-forest",
    linkCode: "https://github.com/enmourn/lost-in-the-forest",
    description: "2D top-down view simulator, created to demonstrate what happens to a person lost in the forest.",
    techStack: "HTML5, TypeScript, ES6, Vite",
    toDo: "Sprite graphics",
  },
  {
    img: "./projects/portfolio.png",
    title: "Portfolio",
    link: "/",
    linkCode: "https://github.com/enmourn/enmourn.github.io",
    description: `It's my web portfolio where you can fine some information about my skills, experience,
      current projects, and send me message`,
    techStack: "React, Styled Components, Vite",
    toDo: "Add light theme and language switcher",
  },
  {
    img: "./projects/grotesquesounds.png",
    title: "Grotesque Sounds",
    link: "http://grotesquesounds.ru",
    description: "Internet store for Grotesque Sounds metal music label",
    techStack: "jQuery, PHP, MySQL",
    toDo: "Restore cart, add new payment methods",
  },
  {
    img: "./projects/metal-circle.png",
    title: "Metal Circle",
    link: "/metalcircle",
    description: "Marketplace for underground metal bands, music lables and fans",
    techStack: "React, Redux Toolkit, TypeScript, Styled Components, Firebase, Vite",
    toDo: "Make basic functionality",
  },
]
